#ifndef __SYSCALL_CONFIG_H
#define __SYSCALL_CONFIG_H

#define SYSCALL_HOLE 248

enum mythread_op {
  MYTHREAD_MUTEX_CREATE,
  MYTHREAD_MUTEX_LOCK,
  MYTHREAD_MUTEX_UNLOCK,
  MYTHREAD_MUTEX_DESTROY,
  MYTHREAD_COND_CREATE,
  MYTHREAD_COND_WAIT,
  MYTHREAD_COND_SIGNAL,
  MYTHREAD_COND_DESTROY,
};

#endif
